### ISSUE TITLE
Not truly random

### ISSUE THREAD

**Issue by gabrieljcs** [jvlsg/roll#1]
The dice rolls in a pseudo-random fashion, *i.e.* not truly random.

Please fix with a better source of entropy (maybe atmospheric data or nuclear decay?).

Thanks in advance.

**Comment by angelorodem** [comment]
I recommend using the webcam as a source of noise, transform the image to HSL and use the lightness channel as noise source, in mixture with the current time and the number of Chinese people in captivity by the gov (change up and down in fast paces)

**Comment by jvlsg** [comment]
This issue has been addressed in the updated README, thank you for your feedback!
